<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <RootNamespace>DatfileCreator.Core</RootNamespace>
        <Authors>Eggman</Authors>
        <Product>Datfile Creator Studio</Product>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ZstdSharp.Port" Version="0.8.5" />
        <PackageReference Include="Blake3" Version="2.1.0" />
        <PackageReference Include="System.IO.Hashing" Version="9.0.0" />
    </ItemGroup>

</Project>
